### PR TITLE
Change header value reading code to use enum constants and lambdas

### PR DESCRIPTION
**Pull request by dwalluck**
Instead of using magic constants in `HeaderValue`, use the types already defined in `Type`.

### CODE REVIEW

**Comment by ctron** [comment]
I like that change. But do we still need that `int` field? Wouldn't it make sense to remove that?

**Comment by dwalluck** [comment]
> I like that change. But do we still need that `int` field? Wouldn't it make sense to remove that?

We might not need it. In that case, I would just change `type` from `int` to `Type` and not add a new field.

But, how do we handle an unknown type? In the current code, it will throw an exception when parsing.

We can add an `UNKNOWN` enum, I guess. We have the `UNKNOWN` class there was well, but I think we have to modify it to hold the original type value `int` since the enum cannot hold it.

**Comment by ctron** [comment]
Yea, if we want to handle unknown ones, then we need a different strategy (I do miss Rust here :grin:).

Maybe an interface, which gets implemented by both the enum, as well as `Custom` class (carrying the int).

**Comment by dwalluck** [comment]
> Maybe an interface, which gets implemented by both the enum, as well as `Custom` class (carrying the int).

What is the goal, to hide the original raw value from the API?

Take a look at how I implemented it now. I stored the type inside the `Unknown` class.

If `this.type =-Type.UNKNOWN`, then you must go through `((Unknown) this.value).getType()` to get the original type.

**Comment by dwalluck** [comment]
@ctron OK, the `Unknown` class now should store the raw `int type` and the raw `byte[] value`.

**Pull request merged**
