### PR TITLE
Use java.nio.file instead of java.io

### PR DESCRIPTION
**Pull request by dwalluck**

### CODE REVIEW

**Review by ctron — CHANGES_REQUESTED** [review]
Looks good. But I would either add some explanation of the deprecation, or drop those functions altogether.

**Comment by dwalluck** [comment]
> Looks good. But I would either add some explanation of the deprecation, or drop those functions altogether.

If you're not concerned with maintaining backwards compatibility, then I would just drop them.

**Comment by ctron** [comment]
> > Looks good. But I would either add some explanation of the deprecation, or drop those functions altogether.
> 
> If you're not concerned with maintaining backwards compatibility, then I would just drop them.

I think we can push out another release, a breaking one.

**Comment by dwalluck** [comment]
> I think we can push out another release, a breaking one.

I've removed the deprecated `File`-based methods.

**Review by ctron — APPROVED** [review]

**Pull request merged**
