### PR TITLE
refactor: Java Security Ultimate Security Repo Scanner 2023

### PR DESCRIPTION
**Pull request by caytec**
Use this link to re-run the recipe: https://app.moderne.io/recipes/builder/TkgUEiqd7?organizationId=RWNsaXBzZSBGb3VuZGF0aW9u

### CODE REVIEW

**Comment by ctron** [comment]
I am sorry, but I don't see the benefit of this change. Could you explain?

**Comment by dwalluck** [comment]
I may not have this entirely correct, but it's something like `File.createTempFile` creates the file with `0666` permissions, but `Files.createTempFile` creates the file with `0600` permissions.

**Comment by ctron** [comment]
> I may not have this entirely correct, but it's something like `File.createTempFile` creates the file with `0666` permissions, but `Files.createTempFile` creates the file with `0600` permissions.

Yes, you're right. Makes sense to me now!

**Comment by ctron** [comment]
@caytec In order to be able to merge this, you need to sign the ECA though: https://www.eclipse.org/legal/ecafaq.php … let me know if you need some help with this.

**Comment by dwalluck** [comment]
@ctron I am going to close this and submit my own PR to move to the `java.nio.files` API more generally (if you don't object).

**Pull request closed without merging**
