### PR TITLE
Change the order of signature processors. See #7

### PR DESCRIPTION
**Pull request by rohit-lshift**

### CODE REVIEW

**Comment by ctron** [comment]
I am not sure I fully understand the reason for this change. If I understand @dwalluck correctly, then the current order is the same as the "official" RPM order.

However I do understand you use case. But I would propose a different solution to that. If I understood correctly, you want to use the Maven plugin to create RPMs, for this old RPM version. If that is the case, I would propose to change both the plugin and the packager RPM library to support enabling/disabling the processors. So that you could enable/disable the SHA1/SHA256 checksums in your case. Would that work for you?

**Comment by rohit-lshift** [comment]
@ctron: Pretty much. If SHA1/SHA256 headers are missing, it should work too.

**Comment by ctron** [comment]
Ok, then I will try to come up with a change that allows you to disable/choose the processors in the maven plugin. I think the packager library already has all those capabilities, but they are not patched through to the maven plugin.

**Comment by rohit-lshift** [comment]
Thanks @ctron!

**Pull request closed without merging**
